version: "2"

plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc.json
  csslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
  nodesecurity:
    enabled: true

checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 10
  method-lines:
    config:
      threshold: 150
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: false
  identical-code:
    enabled: true

ratings:
   paths:
    - "**.js"
    - "**.jsx"
    - "**.css"
    - "**.less"
    - "**.scss"
    - "**.sss"

exclude_paths:
- static/**/*
- third-parties/**/*
- "**/*.min.css"
- "**/*.min.js"
- __tests__/**/*
- __coverage__/**/*