version: "1.0"

stages:
  - build
  - test
  - stage
  - verify
  - release

steps:
  docker:
    title: Building docker container...
    type: build
    stage: build
    #Important: rename this image to to a valid repository in your registry. For example: myUserName/vote
    image_name: curiousprogrammer/helium
    #The directory should be relative to git repository that is used for cloning
    working_directory: ${{main_clone}}
    #Dockerfile location should be relative to the working directory
    tag: ${{CF_BRANCH}}
    dockerfile:
      content: |-
        FROM node:10.15.1-jessie AS builder
        RUN \
          apt-get update && \
        	apt-get -y upgrade && \
        	apt-get -y install sudo

  prepare:
    title: Verifying git status...
    stage: build
    image: ${{docker}}
    commands:
      - git checkout integrate
      - git fetch
      - git branch
      - git status

  build:
    title: Building app...
    stage: build
    image: ${{docker}}
    commands:
      - npm install -g gatsby-cli
      - chmod a+x .run-build.sh
      - ./.run-build.sh

  tests:
    title: Testing app...
    stage: build
    image: ${{docker}}
    commands:
      - npm install -g jest-cli
      - chmod a+x .run-test.sh
      - ./.run-test.sh

  stage:
    title: Creating pull request...
    stage: stage
    image: ${{docker}}
    commands:
    	- chmod a+x .run-pull-request.sh
      - ./.run-pull-request.sh

  verify:
    title: Running tests on PR...
    stage: verify
    image: ${{docker}}
    commands:
    	- echo "Deploy PR to netlify"
      - echo "Page speed test executed on the deployed PR"
      - echo "Any other verification test?"

  release:
    title: Squashing PR onto master...
    stage: release
    image: ${{docker}}
    commands:
    	- echo "Squash"

  tag:
    title: Tagging build...
    stage: release
    image: ${{docker}}
    commands:
    	- echo "Tag"
