language: node_js
node_js:
  - 10.15.0
dist: trusty
sudo: false
before_install:
  - sudo apt-get install chromium-browser xvfb
  - sudo npm install -g lighthouse
  - sudo npm install -g psi
install:
  - npm install
script:
  - npm run test
  - "npm run build"
  - "xvfb-run --server-args='-screen 0, 1024x768x16' \
    chromium-browser --user-data-dir=public/
    --start-maximized \
    --no-first-run \
    --remote-debugging-port=9222 'about:blank'"
  - "lighthouse http://localhost:9222 --chrome-flag '--headless'"
  - "psi http://localhost:9222 --strategy=mobile --threshold=90"
git:
  depth: 3
branches:
  except:
    - /^build.[0-9]/
after_success:
  - "chmod a+x .travis-automerge.sh"
  - "./.travis-automerge.sh"
