language: node_js
node_js:
  - 10.15.0
dist: trusty
sudo: false
before_script:
  - npm install gatsby-cli
script:
  - npm run build
  - npm run test
git:
  depth: 3
after_success:
  - "curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cbillowes/curious-programmer-helium/master/.travis-automerge.sh"
  - "chmod a+x /tmp/travis-automerge"
  - "BRANCHES_TO_MERGE_REGEX='^feature/' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=cbillowes/curious-programmer-helium /tmp/travis-automerge"
