language: node_js
node_js:
  - 10.15.0
before_script:
  - npm install gatsby-cli
script:
  - npm run build
  - npm run test
git:
  depth: 3
after_success:
  - git config --local user.name "Travis CI"
  - git config --local user.email "builds@travis-ci.com"
  - export GIT_TAG=build-1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push origin $GIT_TAG
branches:
  except:
    - /^build-[0-9a-z\-]*/
