language: node_js
node_js:
  - 10.15.0
dist: trusty
env:
  - secure: SFR/7sevo5cp+ErjzhzFHqmS/7WyBWQbQr8GMTCLU2gfH5rxbJfP6aT736iHx6xZih1IMNqpkS2GhtNjXTyn/lV381hBuJXOYNsbOi5HtYqMbEw8I9R/XyRmJMR3ZhtHVO8rcikFAuY+9dPAH+tn0vn4U9QhM0U+1UlAzcLZivW/f4YLqF3C3YRLpLHMjYh451GHQtovOaojWuwFKGMK5iQnv9TRShD6UKTKS6TJmhzAN0nnTKnoa742pzLnXb7I0X6zbiGZJzzAapzP89X8Jz7X09FWQ+ndE9kmNzWvF5KSA3wA1twljSyrOJ3Cj1Y0S7lPTxH0hFAoMnePCQzkT80xeiDW1cOY4dzHgn5WkGAeIMRNgeFgIEYAcR5RgBatkLBmoipDdscGRZg/13dCLUfSa6E3LtBAsOF+pcgW3/STqO4Gu1lkhImFDU/vC5Ks6C5jYao91Wvjf56PGEHXOlvgbohQC41IbcJ3b3NOYmDL4UOfiQA7OQxVRFQnsHx/MYKv96C+tHMsH+IFjjXyzIinxsgH8orQV5DluM9fUb3qPXiwqEn6J/Y6ceLK5bpN7Fch34jrW1ZxQvReMzexNgNC52xLpFvLEYrSK2paM/f7gst3nmF6OCdTqf8Rhd73Z6zfJXqLTh6jEWl5h9Ofhke/X9KEHBDgDjW6U2BXHL8=
sudo: false
script:
  - npm run test
git:
  depth: 3
branches:
  except:
    - /^build.[0-9]/
after_success:
  - "chmod a+x .travis-automerge.sh"
  - "./.travis-automerge.sh"
