language: node_js
node_js:
  - 10.15.0
dist: trusty
sudo: false
git:
  depth: 3
branches:
  except:
    - /^build.[0-9]/
script:
  - npm run test
after_success:
  - npm run test:page-speed
  - ./.travis-automerge.sh
