language: node_js
node_js:
  - 10.15.0
dist: xenial
sudo: false
git:
  depth: 3
branches:
  only:
    - master
    - develop
addons:
  snaps:
    - hub --classic
script:
  - npm run build
  - npm run test
  - bash .travis-pull-request.sh
