language: node_js
node_js:
  - 10.15.0
dist: trusty
sudo: false
git:
  depth: 3
branches:
  only:
    - master
    - develop
script:
  - if $TRAVIS_BRANCH = "develop" && then npm run test
  - if $TRAVIS_BRANCH = "master" && then gatsby build
after_success:
  - if $TRAVIS_BRANCH = "develop" && then git request-pull build.$TRAVIS_BUILD_NUMBER https://github.com/cbillowes/curious-programmer-helium master:develop
after_deploy:
  - npm run test:page-speed
