language: node_js
node_js:
  - 10.15.0
dist: trusty
sudo: false
script:
  - npm run test
git:
  depth: 3
after_success:
  - "cp .travis-automerge.sh /tmp/automerge"
  - "chmod a+x /tmp/travis-automerge"
  - "/tmp/travis-automerge"
