language: node_js
node_js:
  - 10.15.0
dist: xenial
sudo: false
git:
  depth: 3
branches:
  only:
    - master
    - develop
addons:
  snaps:
    - hub
script:
  - npm run build
  - npm run test
after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo build.$TRAVIS_BRANCH ; fi`
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - git tag -a $TAG -m "TravisCI tag for $COMMIT"
  - git push $GITHUB_REPO $TRAVIS_BRANCH:PR origin $TRAVIS_BRANCH $TAG
