language: node_js
node_js:
  - 10.15.0
dist: trusty
sudo: false
script:
  - npm run test
git:
  depth: 3branches:
except:
  - /^build.[0-9]/
after_success:
  - "chmod a+x .travis-automerge.sh"
  - "./.travis-automerge.sh"
