language: node_js
node_js:
  - 10.15.0
dist: trusty
sudo: false
git:
  depth: 3
branches:
  only:
    - master
    - develop
script:
  - npm run build
  - npm run test
deploy:
  on:
    branch: develop
  script: netlify deploy -s $NETLIFY_SITE_ID -a $NETLIFY_AUTH_TOKEN -d /public -p -m "Triggered build.$TRAVIS_BUILD_NUMBER by TravisCI"
